### ISSUE TITLE
mamba devenv is not using mamba

### ISSUE THREAD

**Issue by EricAtORS** [ESSS/conda-devenv#133]
When I run `mamba devenv`, it doesn't use mamba, but conda.

This is the output that I see:
```
 mamba devenv
> Executing: /miniconda3/bin/conda-devenv env update --file /home/eric/environment.yml --prune
```

Simply executing this manually afterward works:
```
mamba env update --file /home/eric/environment.yml --prune
```
    sys.argv is ['/home/eric/miniconda3/bin/conda-devenv']

So I'm not sure where to go next.

**Comment by EricAtORS** [comment]
I dug a bit more, it looks like `mamba devenv` is just calling` /miniconda3/bin/conda-devenv`

**Comment by prusse-martin** [comment]
This is expected.

`conda-devenv` should then be calling mamba to update the env.
https://github.com/ESSS/conda-devenv/blob/2.2.0/conda_devenv/devenv.py#L422-L434

The problem is that mamba detection is failing...
As you pointed out, since it calls `/miniconda3/bin/conda-devenv` that is returned in `env_manager = sys.argv[0]` causing it to fallback to conda (not mamba) to update the resulting env.
That is indeed not the desired result.

**Comment by prusse-martin** [comment]
* Now it is possible to use `mamba`_ with ``conda-devenv`` (#134):
  - Pass ``--env-manager`` in the command-line.
  - Set the ``CONDA_DEVENV_ENV_MANAGER=mamba`` environment variable.
